SELECT C.AUTHOR_ID, C.AUTHOR_NAME, D.CATEGORY, D.TOTAL_SALES
FROM AUTHOR C
JOIN   
    (
        SELECT AUTHOR_ID, CATEGORY, SUM(PRICE * SALES) as TOTAL_SALES
        FROM BOOK A JOIN BOOK_SALES B
        ON A.BOOK_ID = B.BOOK_ID 
        WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
        GROUP BY AUTHOR_ID, CATEGORY
    ) D
ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC