-- 자동차 종류가 세단 또는 SUV 인 자동차 중
-- 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 출력 CAR_ID	CAR_TYPE	FEE
-- 순서 대여 금액 내림, 자동차 종류 오름, 자동차 ID 내림


SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100 ,0) as FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON C.CAR_TYPE = A.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
AND A.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE END_DATE >= '2022-11-01' AND  START_DATE < '2022-12-01'
                     )
AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC,CAR_TYPE, CAR_ID DESC 






