-- 코드를 입력하세요

SELECT 
A.USER_ID,
A.NICKNAME,
CONCAT(A.CITY,' ',A.STREET_ADDRESS1," " ,A.STREET_ADDRESS2) as 전체주소,
CONCAT(LEFT(A.TLNO,3),'-', MID(A.TLNO,4,4) ,'-',RIGHT(A.TLNO,4)) as 전화번호
FROM USED_GOODS_USER A
JOIN(
        SELECT WRITER_ID
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(WRITER_ID) >= 3        
    ) B
ON A.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC


