select case
        WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
        ELSE '4Q'
       END as QUARTER,
       COUNT(*) as ECOLI_COUNT
from ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER
