SELECT A.APNT_NO, B.PT_NAME, B.PT_NO,A.MCDP_CD,C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE A.APNT_CNCL_YN ='N' AND LEFT(A.APNT_YMD,10) = '2022-04-13' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD
