-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.SUM_PRICE AS TOTAL_SALES
FROM USED_GOODS_USER A
JOIN 
(
    SELECT WRITER_ID, SUM(PRICE) as SUM_PRICE
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID 
    HAVING SUM_PRICE>= 700000
) B
ON A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES

