-- 코드를 입력하세요
-- 리뷰를 가장많이 작성한 회원 

SELECT C.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW A 
JOIN 
(
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE C ON C.MEMBER_ID = A.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
