SELECT A.ID, C.FISH_NAME, B.max_length AS LENGTH
FROM FISH_INFO A
JOIN (
        SELECT MAX(LENGTH) max_length, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
     )B
ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.max_length
JOIN FISH_NAME_INFO C
ON A.FISH_TYPE = C.FISH_TYPE
ORDER BY A.ID

