-- 코드를 작성해주세요
# SELECT *
# FROM HR_DEPARTMENT A JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
# JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
# GROUP BY EMP_NO

SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES A JOIN 
    (
        SELECT EMP_NO, SUM(SCORE) as SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) B
ON A.EMP_NO = B.EMP_NO
JOIN HR_EMPLOYEES C ON A.DEPT_ID = C.DEPT_ID
ORDER BY B.SCORE DESC
limit 1